export const strings = {
  // Authentication
  welcome: "Chào mừng đến với MindEnglish",
  tagline: "Học tiếng Anh qua thói quen hàng ngày",
  enterPhone: "Nhập số điện thoại để bắt đầu",
  enterOTP: "Nhập mã xác thực được gửi đến điện thoại",
  phoneNumber: "Số điện thoại (VD: 0901234567)",
  sendOTP: "Gửi mã OTP",
  verifyOTP: "Xác thực OTP",
  enterOTPCode: "Nhập mã OTP 6 số",
  sending: "Đang gửi...",
  verifying: "Đang xác thực...",
  backToPhone: "Quay lại số điện thoại",
  dontHaveAccount: "Chưa có tài khoản? Đăng ký",
  forgotPassword: "Quên mật khẩu?",
  alreadyHaveAccount: "Đã có tài khoản? Đăng nhập",

  // Registration
  createAccount: "Tạo tài khoản",
  fillDetails: "Điền thông tin để bắt đầu",
  fullName: "Họ và tên *",
  email: "Email (tùy chọn)",
  creatingAccount: "Đang tạo tài khoản...",

  // Forgot Password
  resetPassword: "Đặt lại mật khẩu",
  enterPhoneForReset: "Nhập số điện thoại để nhận mã đặt lại",
  enterResetCode: "Nhập mã đặt lại được gửi đến điện thoại",
  createNewPassword: "Tạo mật khẩu mới cho tài khoản",
  sendResetCode: "Gửi mã đặt lại",
  verifyCode: "Xác thực mã",
  newPassword: "Mật khẩu mới",
  confirmPassword: "Xác nhận mật khẩu mới",
  resetting: "Đang đặt lại...",

  // Navigation
  explore: "Khám phá",
  learn: "Học tập",
  profile: "Hồ sơ",

  // Home/Learn Screen
  goodMorning: "Chào buổi sáng,",
  goodAfternoon: "Chào buổi chiều,",
  goodEvening: "Chào buổi tối,",
  keepLearning: "Tiếp tục học,",
  continueLearning: "Tiếp tục học",
  tapToContinue: "Chạm để tiếp tục",
  yourProgress: "Tiến độ của bạn",
  today: "Hôm nay",
  completed: "Hoàn thành",
  courses: "Khóa học",
  thisWeek: "Tuần này",
  listeningTime: "Thời gian nghe",
  currentStreak: "Chuỗi ngày",
  yourCourses: "Khóa học của bạn",
  browseMore: "Xem thêm",
  lessonsCompleted: "bài học hoàn thành",
  next: "Tiếp theo:",

  // Explore Screen
  exploreCourses: "Khám phá khóa học",
  searchCourses: "Tìm kiếm khóa học...",
  all: "Tất cả",
  business: "Kinh doanh",
  dailyLife: "Đời sống",
  grammar: "Ngữ pháp",
  pronunciation: "Phát âm",
  vocabulary: "Từ vựng",
  enrolled: "Đã đăng ký",
  enroll: "Đăng ký",
  continue: "Tiếp tục",
  lessons: "bài học",
  beginner: "Cơ bản",
  intermediate: "Trung cấp",
  advanced: "Nâng cao",

  // Profile Screen
  editProfile: "Chỉnh sửa",
  yourLearningStats: "Thống kê học tập",
  totalTime: "Tổng thời gian",
  dayStreak: "Chuỗi ngày",
  quickSettings: "Cài đặt nhanh",
  pushNotifications: "Thông báo đẩy",
  getReminders: "Nhận lời nhắc luyện tập",
  more: "Thêm",
  settings: "Cài đặt",
  appPreferences: "Tùy chọn ứng dụng",
  supportHelp: "Hỗ trợ & Trợ giúp",
  getHelpContact: "Nhận trợ giúp và liên hệ hỗ trợ",
  privacyPolicy: "Chính sách bảo mật",
  readPrivacyPolicy: "Đọc chính sách bảo mật",
  termsOfService: "Điều khoản dịch vụ",
  readTermsOfService: "Đọc điều khoản dịch vụ",
  rateApp: "Đánh giá ứng dụng",
  helpImprove: "Giúp chúng tôi cải thiện bằng cách đánh giá",
  shareApp: "Chia sẻ ứng dụng",
  shareWithFriends: "Chia sẻ MindEnglish với bạn bè",
  signOut: "Đăng xuất",
  deleteAccount: "Xóa tài khoản",
  deleting: "Đang xóa...",

  // Audio Player
  transcript: "Bản ghi âm",
  notes: "Ghi chú",
  comments: "Bình luận",
  addComment: "Thêm bình luận...",
  writeComment: "Viết bình luận",
  post: "Đăng",
  cancel: "Hủy",
  markAsDone: "Đánh dấu hoàn thành",
  markAsRepeat: "Đánh dấu lặp lại",
  addToFavorites: "Thêm vào yêu thích",
  removeFromFavorites: "Xóa khỏi yêu thích",
  download: "Tải xuống",
  downloaded: "Đã tải",
  downloading: "Đang tải...",
  playbackSpeed: "Tốc độ phát",

  // Comments
  commentsTitle: "Bình luận ({count})",
  noComments: "Chưa có bình luận nào",
  beFirstToComment: "Hãy là người đầu tiên bình luận!",
  reply: "Trả lời",
  like: "Thích",
  timeAgo: {
    justNow: "Vừa xong",
    minuteAgo: "{count} phút trước",
    hourAgo: "{count} giờ trước",
    dayAgo: "{count} ngày trước",
    weekAgo: "{count} tuần trước",
  },

  // Settings
  audioSettings: "Cài đặt âm thanh",
  defaultPlaybackSpeed: "Tốc độ phát mặc định",
  downloadSettings: "Cài đặt tải xuống",
  autoDownload: "Tự động tải xuống",
  autoDownloadDesc: "Tự động tải xuống bài học mới",
  wifiOnly: "Chỉ WiFi",
  wifiOnlyDesc: "Chỉ tải xuống khi kết nối WiFi",
  notifications: "Thông báo",
  appSettings: "Cài đặt ứng dụng",
  darkMode: "Chế độ tối",
  useDarkTheme: "Sử dụng giao diện tối",

  // Support
  supportHelp: "Hỗ trợ & Trợ giúp",
  quickContact: "Liên hệ nhanh",
  emailSupport: "Hỗ trợ Email",
  callUs: "Gọi cho chúng tôi",
  faq: "Câu hỏi thường gặp",
  sendMessage: "Gửi tin nhắn cho chúng tôi",
  category: "Danh mục",
  message: "Tin nhắn",
  describeIssue: "Mô tả vấn đề hoặc câu hỏi của bạn...",
  sendMessage: "Gửi tin nhắn",
  sending: "Đang gửi...",

  // Support Categories
  technicalIssues: "Vấn đề kỹ thuật",
  accountProblems: "Vấn đề tài khoản",
  billingPayments: "Thanh toán & Hóa đơn",
  courseContent: "Nội dung khóa học",
  featureRequest: "Yêu cầu tính năng",
  other: "Khác",

  // Common
  error: "Lỗi",
  success: "Thành công",
  loading: "Đang tải...",
  retry: "Thử lại",
  ok: "Đồng ý",
  yes: "Có",
  no: "Không",
  save: "Lưu",
  edit: "Chỉnh sửa",
  delete: "Xóa",
  share: "Chia sẻ",
  close: "Đóng",

  // Alerts
  confirmSignOut: "Bạn có chắc chắn muốn đăng xuất?",
  confirmDeleteAccount:
    "Bạn có chắc chắn muốn xóa tài khoản? Hành động này không thể hoàn tác và tất cả tiến độ học tập sẽ bị mất.",
  otpSentSuccess: "Mã OTP đã được gửi đến số điện thoại của bạn",
  registrationSuccess: "Đăng ký thành công! Vui lòng xác thực số điện thoại.",
  passwordResetSuccess: "Đặt lại mật khẩu thành công! Vui lòng đăng nhập bằng mật khẩu mới.",
  supportRequestSent: "Yêu cầu hỗ trợ đã được gửi",
  supportRequestDesc: "Cảm ơn bạn đã liên hệ. Chúng tôi sẽ phản hồi trong vòng 24 giờ.",

  // Validation
  pleaseEnterPhone: "Vui lòng nhập số điện thoại",
  pleaseEnterOTP: "Vui lòng nhập mã OTP",
  pleaseEnterName: "Vui lòng nhập họ tên",
  pleaseEnterPassword: "Vui lòng nhập mật khẩu",
  passwordsNotMatch: "Mật khẩu không khớp",
  passwordTooShort: "Mật khẩu phải có ít nhất 6 ký tự",
  invalidOTP: "Mã OTP không hợp lệ. Vui lòng thử lại.",
  phoneNotFound: "Không tìm thấy số điện thoại hoặc gửi mã đặt lại thất bại.",
  fillAllFields: "Vui lòng điền tất cả các trường",
  selectCategoryAndMessage: "Vui lòng chọn danh mục và nhập tin nhắn",
}
